export const tags = [
  'activity book',
  'adoption',
  'adult reference book',
  'adventure',
  'afghanistan',
  'africa',
  'african-american history',
  'air',
  'aliens',
  'alphabet',
  'america',
  'animals',
  'antarctica',
  'arabic',
  'art',
  'art- sculpture',
  'artist',
  'astronomy',
  'atlas',
  'autumn',
  'baby',
  'baking',
  'baseball',
  'bath',
  'bats',
  'beach',
  'bears',
  'bedtime',
  'bees',
  'behavior skills',
  'being yourself',
  'bicycles',
  'biography',
  'birds',
  'birthday',
  'board book',
  'board book shapes',
  'boats',
  'bodily functions',
  'body parts',
  'brazil',
  'breathing',
  'bridges',
  'bugs',
  'bullying',
  'bus',
  'butterfly cycle',
  'cake',
  'caldecott honor',
  'caldecott medal',
  'calendar',
  'camera',
  'camp',
  'camping',
  'canada',
  'caribbean',
  'carpenter',
  'cars',
  'castles',
  'cats',
  'chanukah',
  'chapter book',
  'china',
  'chinese',
  'christmas',
  'circus',
  'cities',
  'civil rights',
  'cleaning',
  'clifford',
  'collective action',
  'colors',
  'community',
  'comparisons',
  'construction',
  'cookie',
  'cooking',
  'counting',
  'countries',
  'courage',
  'cowboys',
  'crafts',
  'culture',
  'curious george',
  'daily routine',
  'death',
  'dentists',
  'dinosaurs',
  'diversity',
  'doctors',
  'dogs',
  'dominican republic',
  'dragons',
  'earth',
  'easter',
  'eating',
  'egypt',
  'elephant and piggie',
  'environmentalism',
  'evolution',
  'fables',
  'fairness',
  'fairy tales',
  'fall',
  'family',
  'fantasy',
  'farm',
  'fears',
  'feelings',
  'fire drill',
  'firefighters',
  'fire truck',
  'fish',
  'fishing',
  'flowers',
  'folktales',
  'folk tales',
  'food',
  'french',
  'french/english',
  'friends',
  'friendship',
  'frogs',
  'funerals',
  'garbage trucks',
  'gardening',
  'gender',
  'german/english',
  'germany',
  'getting lost',
  'getting messy',
  'getting sick',
  'ghana',
  'girl power',
  'graphic novel',
  'greece',
  'growing up',
  'halloween',
  'hats',
  'hawaii',
  'health',
  'helping',
  'hidden picture',
  'holidays',
  'home life',
  'homophones',
  'hospitals',
  'hurricanes',
  'hygiene',
  'illness',
  'imagination',
  'immigrants',
  'insects',
  'interrupting',
  'inventors',
  'ireland',
  'islam',
  'italy',
  'japan',
  'jazz',
  'jealousy',
  'jellyfish',
  'jewish',
  'jokes',
  'jump rope',
  'kenya',
  'knights',
  'korean',
  'kwanzaa',
  'lake',
  'languages',
  'learning to read',
  'lgbt',
  'libraries',
  'life skills',
  'listening',
  'love',
  'magic',
  'manners',
  'mapping',
  'maps',
  'math',
  'measuring',
  'metamorphosis',
  'money',
  'monsters',
  'moon',
  'mountains',
  'mouse',
  'moving',
  'museums',
  'music',
  'myths',
  'native american',
  'nature',
  'nature. science',
  'nature science',
  'navajo',
  'new baby',
  'new york city',
  'nigeria',
  'nonfiction',
  'numbers',
  'nursery rhyme',
  'nursery rhymes',
  'nyc',
  'obama',
  'occupations',
  'ocean',
  'octopus',
  'opposites',
  'otherness',
  'overcoming adversity',
  'oversize',
  'owl',
  'pacifier',
  'passover',
  'patterns',
  'patterns and shapes',
  'penguins',
  'pets',
  'philippines',
  'physics',
  'pigeon',
  'pioneers',
  'pirates',
  'planes',
  'planets',
  'plants',
  'playground',
  'poems',
  'poetry',
  'poets',
  'politics',
  'ponds',
  'pop-up',
  'princesses',
  'professions',
  'pumpkins',
  'rainforest',
  'ramadan',
  'rebus',
  'reference book',
  'relationships',
  'religious',
  'rhyming',
  'riddles',
  'robots',
  'rocks',
  'rodeo',
  'saving up',
  'school',
  'science',
  'sea',
  'seasons',
  'self',
  'senses',
  'sesame street',
  'shapes',
  'sharing',
  'shopping',
  'short stories',
  'siblings',
  'sign language',
  'simple machines',
  'sky',
  'sledding',
  'snakes',
  'snow',
  'social justice',
  'songs',
  'south africa',
  'space',
  'spaceship',
  'spanish',
  'spanish/english',
  'sports',
  'spring',
  'stars',
  'states',
  'strawberry',
  'sukkot',
  'summer',
  'superheroes',
  'surrealism',
  'swahili',
  'tactile',
  'tanzania',
  'teeth',
  'toileting',
  'tools',
  'tornadoes',
  'trains',
  'transportation',
  'travel',
  'trees',
  'trucks',
  'turtles',
  'twins',
  'underwater animals',
  'unlikely animal friendships',
  'urban',
  "valentine's day",
  'vegetables',
  'vietnam',
  'weather',
  'weddings',
  'wheelchair',
  'wheels',
  'wild west',
  'wind',
  'winter',
  'wordless',
  'working parents',
  'world holidays',
  'zaire',
  'zoo',
]
